defaults:
  - _self_
  - model: baseline
  - trainer: default

comp_name: hms-harmful-brain-activity-classification
storage_drive: storage_dimm2

run:
  timestamp: ${now:%Y%m%d-%H%M%S}
  n_folds: 5
  fold: 0
  seed: 48
  logging: True
  run_name: null
  output_dir: /mnt/${storage_drive}/kaggle_output/${comp_name}/${now:%Y%m%d-%H%M%S}
  input_dir: /mnt/${storage_drive}/kaggle_data/${comp_name}

hydra:
  run:
    dir: ${run.output_dir}/fold_${run.fold}/
# sweep:
#   dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
#   subdir: ${hydra.job.num}
